
CREATE TABLE sensors(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title varchar(100) NOT NULL UNIQUE
);

CREATE TABLE measurements(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	value double precision NOT NULL,
	added_at timestamp,
	raining boolean NOT NULL,
	sensor varchar(100) REFERENCES sensors(title)
);